
author = "Andreas"
date= "28/09/2019"
title = "Welcome Dragon Edge Cloud!"
detail = """
  Really excited to relay that the grid will be expanding into Asia
  in the coming months with the help of Colin Baker & Dragon Edge Cloud.
  Don't have much more to share right now but will do so when I can.
  Please reach out to myself or Colin Baker in the meantime.
  """
