
author = "Adnan"
date= "09/10/2019"
title = "Think we have found our exchange!"
detail = """
  The last few months have been super intense hunting for an exchange.
  We have gotten in touch with literally dozens of them – trying to find
  the right match for our project. Nothing is signed yet but as soon as
  I can, I will share more. Good times!
  """
