
author = "Sam"
date= "25/09/2019"
title = "New website is live!"
detail = """
  Friends, we are live with the new threefold.io. You'll notice a new look
  and some new messaging. We think it helps us to simplify our story for
  new audiences. The ThreeFold Network is here!
  """
