
author = "Sam"
date= "01/10/2019"
title = "We have signed on two agencies for support!"
detail = """
  Happy to announce we have signed on Guerrilla Buzz & Token Suite as
  support agencies for the upcoming IEO / TDE. From community-building to
  strategic PR placements to exchange support & more, this will be a big
  help as we continue to navigate this space.
  """
