
author = "Kristof"
date= "08/10/2019"
title = "3Bot is coming alive."
detail = """
  We are really getting there with 3Bot – live now with a functioning
  email, calendar, opendocs, video conferencing & more. I will share out
  a live demo asap. This is big news! Congrats to the team.
  """
